name: BE Conitnuous Integration Workflow

on:
  workflow_dispatch:
  pull_request:
    branches:
      - main
    paths: "starter/backend/**"

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python 3.10
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install pipenv
        run: pip install pipenv --user

      - name: Install flake8
        run: pip install flake8

      - name: Install dependencies
        run: cd ./starter/backend && pipenv install

      - name: Run the linter
        run: cd ./starter/backend && pipenv run lint

  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python 3.10
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install pipenv
        run: pip install pipenv --user

      - name: Install dependencies
        run: cd ./starter/backend && pipenv install

      - name: Run tests
        run: cd ./starter/backend && pipenv run test

  build:
    needs: [lint, test]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python 3.10
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install pipenv
        run: pip install pipenv --user

      - name: Install dependencies
        run: cd ./starter/backend && pipenv install

      - name: Build docker image
        run: cd ./starter/backend && docker build --tag backend-app:latest .

      - name: Run docker container
        run: cd ./starter/backend && docker run -p 5000:5000 --name backend-app -d backend-app